<style type="text/css">
	body{
		background-color:<?php echo $company_fields->bg_color ?>;
	}
	#header{
		width: 80%;
		margin: auto;
		margin-top:20px;
	}
	#header img{
		width: 100%;
		height: 220px;
	}
	#header .logo{
		background-color:white;
		margin:0px;
	}
	#header .col-md-2,#header .col-md-10{
		padding:0px;
		margin:0px;		
	}
	.mensaje{
		background-color: white;
		padding:20px;
		border:1px solid #8d8986;
		margin:auto;
		width: 80%;
		margin-top:20px;
	}
	.form-horizontal label{
		color:white;
		font-weight: 100;
	}
	.form-control{
		border-radius: 0px;
	}
		.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 10px black;
	}
.modal-content  {
    -webkit-border-radius: 0px !important;
    -moz-border-radius: 0px !important;
    border-radius: 0px !important; 
}
</style>
<?php View::content() ?>
<div id="header">
	<div class="row">
		<div class="col-md-2 logo">
			<?php echo Html::img($company_fields->logo_url) ?>
		</div>
		<div class="col-md-10">
			<?php echo Html::img($company_fields->bg_url) ?>
		</div>
	</div>

</div>
<div class="row">
	
	<div class="col-md-12">
		<div class="mensaje ">
			
		<p>
			<?php echo $company_fields->texto ?>
		</p>
		</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<form class="form-horizontal" method="POST">
		<div class="row">
			
			<div class="col-md-8">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
			    <div class="col-sm-10">
			    	<input type="hidden" value="<?php echo $company->id ?>" name="company_perfiles[company_id]">
			    	<input type="hidden" value="<?php echo Auth::get('id') ?>" name="company_perfiles[user_id]">
			      <input type="text" class="form-control" name="company_perfiles[nombre]"  id="inputEmail3" placeholder="Nombre">
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Sexo</label>
			    <div class="col-sm-10">
			    	<select name="company_perfiles[sexo]"  class="form-control" required="required" id="">
			    		<option value="">Seleccione</option>
			    		<option value="F">Femenino</option>
			    		<option value="M">Masculino</option>
			    	</select>
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			
			<div class="col-md-8">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">E-mail</label>
			    <div class="col-sm-10">
			      <input type="email" class="form-control" name="company_perfiles[email]" id="inputEmail3" placeholder="E-mail">
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Edad</label>
			    <div class="col-sm-10">
			      <input type="number" min='18' max="80" class="form-control" name="company_perfiles[edad]" id="inputEmail3" placeholder="Edad">
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			
			<div class="col-md-6">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-4  text-left">Teléfono 1</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" name="company_perfiles[telefono1]" id="inputEmail3" placeholder="Teléfono 1">
			    </div>
			  </div>
			</div>
			<div class="col-md-6">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-4  text-left">Teléfono 2</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" name="company_perfiles[telefono2]" id="inputEmail3" placeholder="Teléfono 2">
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-1 control-label">Puesto</label>
			    <div class="col-sm-11">
			      <select name="company_perfiles[puesto]" required id="" class="form-control">
			      	<option value="">Selecciona</option>
			      	<?php foreach ($company_puesto as $key => $value): ?>
			      		<option value="<?php echo $value->puesto ?>"><?php echo $value->puesto ?></option>
			      	<?php endforeach ?>
			      </select>
			    </div>
			  </div>				
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Experiencia Laboral</label>
			    <div class="col-sm-10">
			      <textarea name="company_perfiles[experiencia]" id="" cols="30" rows="5" class="form-control"></textarea>
			    </div>
			  </div>				
			</div>
		</div>

		<div class="row">
			<div class="col-md-6"></div>
			<div class="col-md-6">

			</div>
		</div>
		<div class="row">
			
			<div class="col-md-4">
				<div class="form-group">
			    <div class="col-md-8">
			      <label><input type="checkbox" required id="checkbox_aviso1">&nbsp;<a href="#" style="font-size:13px" data-toggle="modal" data-target="#myModal">Aviso de Privacidad</a></label>
			      <!-- Button trigger modal -->

				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Aviso de Privacidad</h4>
				      </div>
				      <div class="modal-body">
				        <p>
				        	<?php echo $company_fields->aviso_privacidad ?>
				        </p>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				        <button type="button" class="btn btn-success" id="aviso1" onClick="$('#checkbox_aviso1').attr('checked',true);$('#myModal').modal('hide')">Acepto</button>
				      </div>
				    </div>
				  </div>
				</div>
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			   
			    <div class="col-md-8">
			      <label><input type="checkbox" required>&nbsp;<a style="font-size:13px" href="https://empresas.empleolisto.com.mx/aviso" target="_blank">Aviso de Privacidad</a></label>
			    </div>
			  </div>			
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn_crear_empresa">Enviar</button>
					</div>
				</div>
			</div>
		</div>
		
		</form>
	</div>
	<div class="col-md-3"></div>
</div>
