<style type="text/css">
	body{
		background:<?php echo $company_fields->bg_color ?> url("<?php echo PUBLIC_PATH ?>img/fondo_texturizado.png");
		position: relative;
	}
	#header{
		width: 80%;
		margin: auto;
		margin-top:20px;
	}
	#header img{
		width: 100%;
		height: 220px;
	}
	#header .logo{
		background-color:white;
		margin:0px;
	}
	#header .col-md-2,#header .col-md-10{
		padding:0px;
		margin:0px;		
	}
	.mensaje{
		background-color: white;
		padding:20px;
		border:1px solid #8d8986;
		margin:auto;
		width: 80%;
		margin-top:20px;
	}
	.form-horizontal label{
		color:white;
		font-weight: 100;
	}
	.form-control{
		border-radius: 0px;
	}
		.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 10px black;
	}
	h1{
		font-weight: bold;
	}
</style>
<div id="header">
	<div class="row">
		<div class="col-md-2 logo">
			<?php echo Html::img($company_fields->logo_url) ?>
		</div>
		<div class="col-md-10">
			<?php echo Html::img($company_fields->bg_url) ?>
		</div>
	</div>

</div>
<div class="row">
	
	<div class="col-md-12">
		<div class="mensaje ">
			<h1 class="text-center">Gracias</h1>
			<br>
			<p>
				<?php echo $company_fields->agradecimiento ?>
			</p>
		</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
				<div class="form-group">
					<div class="text-center">
						<?php echo Html::link("RS/?p=".$company->url,"Nuevo",'class="btn_crear_empresa"') ?>
					</div>
				</div>
	</div>
	<div class="col-md-4"></div>
</div>
<?php View::content() ?>