<style type="text/css">
	body{
		background-color:#1f8cd2;
	}
	#header{
		width: 80%;
		margin: auto;
		margin-top:20px;
	}
	#header img{
		width: 100%;
		height: 220px;
	}
	#header .logo{
		background-color:white;
		margin:0px;
	}
	#header .col-md-2,#header .col-md-10{
		padding:0px;
		margin:0px;		
	}
	.mensaje{
		background-color: white;
		padding:20px;
		border:1px solid #8d8986;
		margin:auto;
		width: 80%;
		margin-top:20px;
	}
	.form-horizontal label{
		color:white;
		font-weight: 100;
	}
	.form-control{
		border-radius: 0px;
	}
		.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 10px black;
	}
	h1{
		font-weight: bold;
	}
</style>
<div id="header">
	<div class="row">
		<div class="col-md-2 logo">
			<?php echo Html::img("RECRUITMENT STATION/sears-logo.png") ?>
		</div>
		<div class="col-md-10">
			<?php echo Html::img("RECRUITMENT STATION/shutterstock_2130063162-01.jpg") ?>
		</div>
	</div>

</div>
<div class="row">
	
	<div class="col-md-12">
		<div class="mensaje ">
			<h1 class="text-center">Gracias</h1>
			<br>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero distinctio nemo unde magnam, ipsa, obcaecati rerum quasi illum eum praesentium sunt tempora facilis tenetur. Sapiente eum molestias, dicta corporis mollitia!
		</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
				<div class="form-group">
					<div class="text-center">
						<button type="submit" class="btn_crear_empresa">Nuevo</button>
					</div>
				</div>
	</div>
	<div class="col-md-4"></div>
</div>
<?php View::content() ?>