  <header>
    <div class="row">
      <div class="col-md-3 logo">
        <h1>empleolisto <br><small>Recruitment Station</small></h1>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-4">
            <?php echo Html::link("","<p>Nuestras Empresas</p>") ?>
          </div>
          <div class="col-md-4">
          <?php echo Html::link("","¿Cómo Funciona?") ?>
          </div>
          <div class="col-md-4">
          <?php echo Html::link("","Contáctanos") ?>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="pull-right div_inicio_sesion">
          <?php echo Html::link("RS/login","Iniciar Sesión") ?>
        </div>
        <div class="clearfix"></div>
      </div>
  		<div class="clearfix"></div>

    </div>
  </header>

<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}

	.fondo{
		padding-top: 10px;
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/man-people-space-desk-1024x683.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		height: 100%;

	}
	#capa{
		position: relative;
		height: auto;
		width:80%;
		margin:auto;
		background: rgba(255, 255, 255, 0.5);
		border-radius: 2px;
		box-shadow: 2px 2px 10px;
		margin-top: 2%;
		margin-bottom: 2%;

	}
	#capa p,#capa li{
		font-size: 22px;
	}
	#capa_letras{
		position: relative;
		padding: 22px;
		margin-bottom: 60px;
	}
	#franja{
		position: relative;
		height: auto;
		width: 100%;
		background-color: white;
		bottom:80px;
		text-align: center;
	}
	.logos{
		padding:10px;
		display: inline-block;

	}
	.logos img{
		height: 80px;
		margin-right: 10px;
	}
	.inditex{
		height: 30px !important;
	}

</style>

<div class="fondo">
	<div id="capa">
		<div id="capa_letras">
			<p>Este producto esta diseñado para fábricas, grandes almacénes y turismo.<br>
			¡Olvidate del papel y dile hola a lo más nuevo en tecnología!</p>
			<ul>
				<li>Postúlate más rápido</li>
				<li>Encuentra mejores ofertas</li>
			</ul>
		</div>
		<div id="franja">
			<div class="logos">
				<?php echo Html::img("officedepot.png") ?>
				<?php echo Html::img("lumen.png") ?>
				<?php echo Html::img("gameplanet.png") ?>
				<?php echo Html::img("sears.png") ?>
				<?php echo Html::img("las-alitas.png") ?>
				<?php echo Html::img("inditex.png","","class='inditex'") ?>
				<?php echo Html::img("farmaciasdelahorro.jpg") ?>
			</div>
		</div>
		
	</div>
	<center>
		<a href="<?php echo PUBLIC_PATH ?>RS/login" class='boton_app'>Login</a>
	</center>
</div>
<?php View::content() ?>
