<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	.fondo{
		padding:40px;
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo login-03.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		height: 100%;

	}
	.user_icon{
		width: 150px;
	}
	.logo_title{
		display: inline-block;
	}
	.logo_title span{
		color:white;
		font-size: 30px;
		font-weight: 500;
	}
	.caja_inputs{

		width: 400px;
		/*border:1px solid black;*/
		margin:auto;
		margin-top:100px;
	}
	.fondo label{
		color:white;
		font-weight: 100;
	}
</style>
<div class="fondo">
	<div class="logo_title">
		<?php echo Html::img("RECRUITMENT STATION/iconos2_byn-05.png","","class='user_icon'") ?>
		<span>Login</span>
	</div>
	<div class="caja_inputs">
	<?php echo Form::open("","post","class='form-horizontal' id='form-login'") ?>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">User</label>
		    <div class="col-sm-10">
		      <input type="email" class="form-control" id="inputEmail3" placeholder="User">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
		    <div class="col-sm-10">
		      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
		    </div>
		  </div>
		
		  <center>
		  		<br>
		      	<a class="boton_app" onclick='$("#form-login").submit();return false;'>Entrar</a>
		  </center>
		</form>
	</div>
</div>