<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	header{
		background-color:#f3910c;
		height: 110px;
		width: 100%;
		box-shadow: 2px 2px 10px;
	}
	.fondo{
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo_reclutador-05.jpg");
		background-repeat:no-repeat;
		background-size:cover;

	}
	.logo{
		padding:0 !important;
	}
	header a,header p{
		color:white;
		vertical-align: center;
		line-height: 100px;
		font-size: 16px;
	}
	#titulo_pagina{
		color:white;
		font-size: 40px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#titulo_pagina_2{
		color:white;
		font-size: 20px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#form_registro{
		width: 100%;
	}
	#form_registro label{
		font-weight: 100;
		color: white;
	}
	#form_registro input[type="checkbox"]{
	  -ms-transform: scale(2); /* IE */
	  -moz-transform: scale(2); /* FF */
	  -webkit-transform: scale(2); /* Safari and Chrome */
	  -o-transform: scale(2); /* Opera */
	  padding: 10px;
	}
	.checks{
		  -ms-transform: scale(2); /* IE */
		  -moz-transform: scale(2); /* FF */
		  -webkit-transform: scale(2); /* Safari and Chrome */
		  -o-transform: scale(2); /* Opera */
		  padding: 10px;
		  border:1px solid white;
		  background-color: red;
	}
	.checks_text{
		text-align: center;
		color:white;
	}
	.checkboxes{
		margin-top: 20px;
	}
	.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 5px grey;
	}
	.fondo_izquierdo{
		background: rgba(255, 255, 255, 0.5);
		height: 100%;
		opacity: 0.5;
		border-right: 1px solid white;
	}
	.fondo_izquierdo ul,.fondo_derecho ul{
		margin-top:100px;
		list-style: none;
	}
	.fondo_izquierdo ul li{
		color:grey;
		text-align: right;
		margin-bottom:150px;
	}
	.fondo_derecho ul li{
		color:grey;
		text-align: right;
		margin-bottom:80px;		
	}
	.logo_empresa{
		width: 260px;
	}
	#fondo_perfil{
		width: 100px;
		height: 100px;
		background-color: white;
	}
</style>

<div class="fondo">

	<header>
	    <div class="row">
	      <div class="col-md-3 col-xs-3 logo">
	        <h1>empleolisto <br><small>Recruitment Station</small></h1>
	      </div>
	      <div class="col-md-6 col-xs-6">
	        <div class="row">
	          <div class="col-md-4 col-xs-4">
	            <?php echo Html::link("","<p>Opciones</p>") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verPerfiles","Ver perfiles") ?>
	          </div>
	       
	        </div>
	      </div>
	      <div class="col-md-3 col-xs-3">
	        <div class="pull-right div_inicio_sesion">
	          <?php echo Html::link("","Log out") ?>
	        </div>
	        <div class="clearfix"></div>
	      </div>
	      <div class="clearfix"></div>
	    </div>
	</header>

	<div class="row">
		<div class="col-md-2 fondo_izquierdo">
			<ul>
				<li>Logo:</li>
				<li>Back:</li>
				<li>Texto:</li>
				<li>Puesto:</li>
				<li>Agradecimiento:</li>
				<li>Aviso de Privacidad:</li>
			</ul>
		</div>
		<div class="col-md-10 fondo_derecho">
			<ul>
				<li>
					<div class="row">
						<div class="col-md-6 text-center">
							<img src="<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/sears-logo.png" alt="TU Logo" class="img-thumbnail logo_empresa">
						</div>
						<div class="col-md-6 form-inline text-center">
							<label>Cambio de Password</label>
							<input type="text" class="form-control" placeholder="Cambiar Contraseña" style="width:50%">
						</div>
					</div>
				</li>
				<li>
					<div class="row">
						<div class="col-md-4 text-center">
							<input type="color" onchange="$('#fondo_perfil').css('backgroundColor',$(this).val())">
							<div id="fondo_perfil">
								
							</div>
						</div>
						<div class="col-md-4">
							
						</div>
						<div class="col-md-4">
								
						</div>
					</div>					
				</li>
				<li>
					
				</li>
				<li>
					
				</li>
				<li>
					
				</li>
				<li>
					
				</li>
			</ul>
		</div>
	</div>	

</div>
<?php View::content() ?>