<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	header{
		background-color:#f3910c;
		height: 110px;
		width: 100%;
		box-shadow: 2px 2px 10px;
	}
	.fondo{
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo_reclutador-05.jpg");
		background-repeat:no-repeat;
		background-size:cover;

	}
	.logo{
		padding:0 !important;
	}
	header a,header p{
		color:white;
		vertical-align: center;
		line-height: 100px;
		font-size: 16px;
	}
	#titulo_pagina{
		color:white;
		font-size: 40px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#titulo_pagina_2{
		color:white;
		font-size: 20px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#form_registro{
		width: 100%;
	}
	#form_registro label{
		font-weight: 100;
		color: white;
	}
	#form_registro input[type="checkbox"]{
	  -ms-transform: scale(2); /* IE */
	  -moz-transform: scale(2); /* FF */
	  -webkit-transform: scale(2); /* Safari and Chrome */
	  -o-transform: scale(2); /* Opera */
	  padding: 10px;
	}
	.checks{
		  -ms-transform: scale(2); /* IE */
		  -moz-transform: scale(2); /* FF */
		  -webkit-transform: scale(2); /* Safari and Chrome */
		  -o-transform: scale(2); /* Opera */
		  padding: 10px;
		  border:1px solid white;
		  background-color: red;
	}
	.checks_text{
		text-align: center;
		color:white;
	}
	.checkboxes{
		margin-top: 20px;
	}
	.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 5px grey;
	}
	.fondo_izquierdo{
		background: rgba(255, 255, 255, 0.5);
		height: 100%;
		opacity: 0.5;
		border-right: 1px solid white;
	}
	.fondo_izquierdo ul,.fondo_derecho ul{
		margin-top:100px;
		list-style: none;
	}
	.fondo_izquierdo ul li{
		color:grey;
		text-align: right;
		margin-bottom:200px;
	}
	.fondo_derecho ul li{
		color:grey;
		text-align: right;
		margin-bottom:80px;		
	}
	.logo_empresa{
		width: 260px;
	}
	#fondo_perfil{
		width: 100px;
		height: 100px;
		background-color: white;
		margin: auto;
		padding:6px;
	}
	.btn-menos,.btn-mas{
		border-radius: 10px;
		border:0px;
		color:white;
		width: 20px;
		height: 20px;
		font-weight: bold;
		font-size: 14px;
	}
	.btn-menos:active,.btn-mas:active{
		box-shadow: 2px 2px 6px grey;
		border:1px solid grey;
	}
	.btn-menos{
		background-color: red;
	}
	.btn-mas{
		background-color: green;
	}
	.cajero_div{
		color:black;
		position: relative;
	}
	
	.cajero_box{

		font-size: 12px;
		color:white;
		border:2px solid #a6a6a6;
		padding:8px;
		background-color: #7f7f7f;
	}
	.puestos_div{
		padding:6px;
		background-color: white;
		height: 96px;
		box-shadow: 2px 2px 10px grey;
	}
	.puestos_div label{
		font-size: 10px;
		margin-bottom: 0px;
	}
</style>
<?php View::content() ?>
<div class="fondo">

	<header>
	    <div class="row">
	      <div class="col-md-3 col-xs-3 logo">
	        <h1>empleolisto <br><small>Recruitment Station</small></h1>
	      </div>
	      <div class="col-md-6 col-xs-6">
	        <div class="row">
	          <div class="col-md-4 col-xs-4">
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verPerfiles","Ver perfiles") ?>
	          </div>
	       
	        </div>
	      </div>
	      <div class="col-md-3 col-xs-3">
	        <div class="pull-right div_inicio_sesion">
	          <?php echo Html::link("RS/logout","Log out") ?>
	        </div>
	        <div class="clearfix"></div>
	      </div>
	      <div class="clearfix"></div>
	    </div>
	</header>

	<div class="row">
		<div class="col-md-2 fondo_izquierdo">
			<ul>
				<li>Logo:</li>
				<li>Back:</li>
				<li>Texto:</li>
				<li>Puesto:</li>
				<li>Agradecimiento:</li>
				<li>Aviso de Privacidad:</li>
			</ul>
		</div>
		<?php echo Form::openMultipart() ?>
		<div class="col-md-10 fondo_derecho">
			<ul>
				<li>
					<div class="row">
						<div class="col-md-4 text-center">
							<img src="<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/sears-logo.png" alt="TU Logo" class="img-thumbnail logo_empresa">
							<br>
							<br>
							<?php echo Form::file('logo') ?>
						</div>
						<div class="col-md-4 form-inline text-center">
							<label>Cambio de Password</label>
							<input type="text" class="form-control" name="password" placeholder="Cambiar Contraseña" style="width:50%">
						</div>
					</div>
				</li>
				<li>
					<div class="row">
						
						<div class="col-md-4 text-center">
							<div id="fondo_perfil" class='img-thumbnail'>
								<p>Selecciona un color de fondo abajo!</p>
							</div><br>
							<input type="color" onchange="$('#fondo_perfil').css('backgroundColor',$(this).val())">
						</div>
						<div class="col-md-5">
						<div class="row">
							<div class="col-md-10">
								<?php echo Html::img("fondo_trabajando.jpg","",'class="img-thumbnail"') ?>
								<br><br>
								<?php echo Form::file('logo_fondo') ?>
							</div>
							<div class="col-md-2">
								<span style="font-size: 9px;color:black;">650x140 px</span>
							</div>
						</div>
						</div>
						<div class="col-md-3">
								
						</div>
					</div>					
				</li>
				<li>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-6">
							<?php echo Form::textarea("texto","class='form-control'") ?>
							
						</div>
						<div class="col-md-2 text-left">
							<span style="font-size: 9px;color:black;">140 caracteres</span>
						</div>
						<div class="col-md-2">
					</div>
				</li>
				<li>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-6 puestos_div">
							<div class="row">
								<div class="col-md-3 text-left">
									<label><input type="checkbox">&nbsp;Cajero</label><br>
									<label><input type="checkbox">&nbsp;Limpieza</label><br>
									<label><input type="checkbox">&nbsp;Chofer</label><br>
									<label><input type="checkbox">&nbsp;Operador de Línea</label><br>
								</div>
								<div class="col-md-3 text-left">
									<label><input type="checkbox">&nbsp;Cocina</label><br>
									<label><input type="checkbox">&nbsp;Mesero</label><br>
									<label><input type="checkbox">&nbsp;Chef</label><br>
								</div>
								<div class="col-md-3 text-left">
									<label><input type="checkbox">&nbsp;Edecán</label><br>
									<label><input type="checkbox">&nbsp;Ventas</label><br>
									<label><input type="checkbox">&nbsp;Promotor</label><br>
								</div>
								<div class="col-md-3 text-left">
									<label><input type="checkbox">&nbsp;Barista</label><br>
									<label><input type="checkbox">&nbsp;Bartender</label><br>
									<label><input type="checkbox">&nbsp;Seguridad</label><br>
								</div>
							</div>
							
						</div>
						<div class="col-md-3 cajero_div ">
								Agregar: <span class='cajero_box'>Cajero <button class="btn-mas">+</button> <button class="btn-menos">-</button> </span>
						</div>
						<div class="col-md-1"></div>
					</div>					
				</li>
				<li>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-6">

							<?php echo Form::textarea("agradecimiento","class='form-control' rows='4'","Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam accusamus incidunt, praesentium modi, dolorem blanditiis eligendi qui doloribus perspiciatis unde, laboriosam excepturi sapiente") ?>
							
						</div>
						<div class="col-md-2 text-left">
							<!--<span style="font-size: 9px;color:black;">140 caracteres</span>-->
						</div>
						<div class="col-md-2"></div>
					</div>					
				</li>
				<li>
						<div class="col-md-2"></div>
						<div class="col-md-6">

							<?php echo Form::textarea("aviso_privacidad","class='form-control' rows='4'","Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam accusamus incidunt, praesentium modi, dolorem blanditiis eligendi qui doloribus perspiciatis unde, laboriosam excepturi sapiente") ?>
							
						</div>
						<div class="col-md-2 text-left">
							<!--<span style="font-size: 9px;color:black;">140 caracteres</span>-->
						</div>
						<div class="col-md-2"></div>	
						<div class="clearfix"></div>				
				</li>
				
			</ul>
			<div class="row">
				<div class="col-md-12 text-center">
					<button type="submit" class="btn_crear_empresa">Guardar</button>
				</div>
			</div>
			</form>
		</div>
	</div>	

</div>
