<?php echo Tag::js("jquery.dataTables.min") ?>
<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	header{
		background-color:#1e96ce;
		height: 100px;
		width: 100%;
		box-shadow: 2px 2px 10px;
	}
	.fondo{
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo_superadmin-06.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		height: 100%;

	}
	.logo{
		padding:0 !important;
	}
	header a,header p{
		color:white;
		vertical-align: center;
		line-height: 100px;
		font-size: 16px;
	}
	#titulo_pagina{
		color:white;
		font-size: 40px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#titulo_pagina_2{
		color:white;
		font-size: 20px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#form_registro{
		width: 100%;
	}
	#form_registro label{
		font-weight: 100;
		color: white;
	}
	#form_registro input[type="checkbox"]{
	  -ms-transform: scale(2); /* IE */
	  -moz-transform: scale(2); /* FF */
	  -webkit-transform: scale(2); /* Safari and Chrome */
	  -o-transform: scale(2); /* Opera */
	  padding: 10px;
	}
	.checks{
		  -ms-transform: scale(2); /* IE */
		  -moz-transform: scale(2); /* FF */
		  -webkit-transform: scale(2); /* Safari and Chrome */
		  -o-transform: scale(2); /* Opera */
		  padding: 10px;
		  border:1px solid white;
		  background-color: red;
	}
	.checks_text{
		text-align: center;
		color:white;
	}
	.checkboxes{
		margin-top: 20px;
	}
	.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 5px grey;
	}
	.table thead{
		background-color:#ff7e03;
		color:white;
	}
	.iconos_sexo{
		width: 20px;
	}
	.lightSlider img{
		width: 20px;
	}
	.lSAction a:hover,.lSAction a:hover{
		color: #ff7e03 !important;
			
	}

	.lSNext span,.lSPrev span{
		top: 14%;
		font-size: 20px;
		font-weight: bold;
	}
	
	.lSNext,.lSPrev{
		color: #ff7e03;
	}
</style>

<div class="fondo">

	<header>
	    <div class="row">
	      <div class="col-md-3 col-xs-3 logo">
	      <br>
	      	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo Html::img("logo blanco-02.png","","width='180'") ?>
	      </div>
	      <div class="col-md-6 col-xs-6">
	        <div class="row">
	          <div class="col-md-4 col-xs-4">
	            <?php echo Html::link("RS/miPerfil","<p>Opciones</p>") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php //echo Html::link("RS/verPerfiles","Ver perfiles") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php //echo Html::link("RS/verEmpresas","Ver Empresas") ?>
	          </div>
	        </div>
	      </div>
	      <div class="col-md-3 col-xs-3">
	        <div class="pull-right div_inicio_sesion">
	          <?php echo Html::link("RS/logout","Log out") ?>
	        </div>
	        <div class="clearfix"></div>
	      </div>
	      <div class="clearfix"></div>
	    </div>
	</header>
	
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 text-center">
			<br>
			<?php if (count($perfiles)): ?>
				
			
			<form class="form-inline">
			  <div class="form-group">
			    <label style="color:white;font-weight: 100">Puesto</label>
			    <select name="puesto" onChange="$(this).parent().parent().submit()" class="form-control" id="">
			    	<option value="">Seleccione</option>
			    	<?php foreach ($puestos as $key => $value): ?>
			    		<?php if (isset($_GET['puesto']) and $_GET['puesto'] == $value->puesto): ?>
				    		<option value="<?php echo $value->puesto ?>" selected><?php echo $value->puesto ?></option>

			    		<?php else: ?>
				    		<option value="<?php echo $value->puesto ?>"><?php echo $value->puesto ?></option>
			    		<?php endif ?>
			    	<?php endforeach ?>
			    </select>
			  </div>
			  <div class="form-group">
			    <button class="btn btn-default" name="excel" value="1">Descargar</button>
			  </div>
			</form>
			<?php endif ?>
			<br>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<?php if (count($perfiles)): ?>
				
			
			<table class="table datatable">
				<thead>
					<th>Nombre</th>
					<th>Edad</th>
					<th>E-mail</th>
					<th>Teléfono</th>
					<th>Fecha de Aplicación</th>
					<th>Sexo</th>
					<th>Status</th>
					<th>Comentarios</th>
					<th></th>
				</thead>
				<?php for($i=0;$i<count($perfiles);$i++): ?>
				
						<tr style="background-color: white">
						<td> <?php echo $perfiles[$i]->nombre ?></td>
						<td><?php echo $perfiles[$i]->edad ?></td>
						<td><?php echo $perfiles[$i]->email ?></td>
						<td><?php echo $perfiles[$i]->telefono1 ?> | <?php echo $perfiles[$i]->telefono2 ?></td>
						<td><?php echo $perfiles[$i]->created ?></td>
						<td>
						<?php if ($perfiles[$i]->sexo == "M"): ?>
						<?php echo Html::img("RECRUITMENT STATION/iconos h y m-01.png","","class='iconos_sexo'") ?>
						<?php else: ?>
						<?php echo Html::img("RECRUITMENT STATION/iconos h y m-02.png","","class='iconos_sexo'") ?>

						<?php endif ?>
							
						</td>
						<td>
							<div style="width:100px">
								
							<ul class="lightSlider">
							  <li><a href="">&nbsp;</a></li>

							  <?php if ($perfiles[$i]->no_aplica): ?>
							  	<li><a href="#" class="no_aplica" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-02.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="no_aplica" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-02.png') ?></a></li>
							  <?php endif ?>


							  <?php if ($perfiles[$i]->aplico): ?>
							  	<li><a href="#" class="aplico" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-03.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="aplico" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-03.png') ?></a></li>
							  <?php endif ?>

							  <?php if ($perfiles[$i]->llamar): ?>
							  	<li><a href="#" class="llamar" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-01.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="llamar" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-01.png') ?></a></li>
							  <?php endif ?>


							  <?php if ($perfiles[$i]->entrevista1): ?>
							  	<li><a href="#" class="entrevista1" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-04.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="entrevista1" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-04.png') ?></a></li>
							  <?php endif ?>


							  <?php if ($perfiles[$i]->entrevista2): ?>
							  	<li><a href="#" class="entrevista2" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-05.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="entrevista2" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-05.png') ?></a></li>
							  <?php endif ?>

							  <?php if ($perfiles[$i]->medico): ?>
							  	<li><a href="#" class="medico" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-06.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="medico" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-06.png') ?></a></li>
							  <?php endif ?>

							  <?php if ($perfiles[$i]->documentos): ?>
							  	<li><a href="#" class="documentos" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-08.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="documentos" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-08.png') ?></a></li>
							  <?php endif ?>


							  <?php if ($perfiles[$i]->contrato): ?>
							  	<li><a href="#" class="contrato" accion="0" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2-07.png') ?></a></li>
								<?php else: ?>
									<li><a href="#" class="contrato" accion="1" id="<?php echo $perfiles[$i]->id ?>"><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-07.png') ?></a></li>
							  <?php endif ?>

							  <li><a href="#">&nbsp;</a></li>

							</ul>
							</div>							  
						</td>
						<td style="width:200px" contenteditable="true" class="comentarios" id="<?php echo $perfiles[$i]->id ?>">
							<?php if (!$perfiles[$i]->comentario): ?>
								Deja un Comentario
							<?php else: ?>
								<?php echo $perfiles[$i]->comentario ?>
							<?php endif ?>
						</td>
						<td>

							<button type="button" class="btn btn-default popup" data-toggle="popover" data-placement="left" title="Experiencia Laboral" data-content="<?php echo $perfiles[$i]->experiencia ?>">Experiencia</button>
						</td>
					</tr>
				<?php endfor; ?>
			</table>
		<?php else: ?>
			<center>
				<h3>No se Encontraron Registros</h3>
			</center>
			<?php endif ?>
		</div>
		<div class="col-md-1"></div>
		
	</div>		


</div>
<style type="text/css">
	.dataTables_paginate a{
		padding-left:10px;
	}
	.dataTables_paginate a:hover{
		cursor:pointer;
	}
</style>
<?php View::content() ?>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>lightslider/dist/css/lightslider.min.css"">
<!-- <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>bootstrap/js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>lightslider/dist/js/lightslider.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>bootstrap/js/tooltip.js"></script>
<script type="text/javascript">
$(document).ready(function(){
		$(".datatable").DataTable({
		language:{
    "sProcessing":     "Procesando...",
    "sLengthMenu":     "Mostrar _MENU_ registros",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
        "sFirst":    "Primero",
        "sLast":     "Último",
        "sNext":     "Siguiente",
        "sPrevious": "Anterior"
    },
    "oAria": {
        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
}
	});
	$('.lightSlider').lightSlider({
	    item: 3,
	    pager: false,
	    autoWidth: false,
    prevHtml : '<span class="glyphicon glyphicon-chevron-left"></span>',
    nextHtml : '<span class="glyphicon glyphicon-chevron-right"></span>'
	});

$("body").on("blur",".comentarios",function(){
		console.log("EDITO!")
		var text = $.trim($(this).text());
		var este = $(this);
		$.ajax({
			url:"<?php echo PUBLIC_PATH ?>company_perfiles/editarComentario/"+$(this).attr("id"),
			type:"POST",
			data:{comentario:text},
			dataType:"json",
			success:function(r){
				if (r.correcto === false) {
					alert("Ocurrio un error guardando el comentario!");
					este.text("Deja un Comentario");
				}
			}
		});
	})
	$("body").on("click",".lightSlider a",function(e){
		e.preventDefault();
		var campo = $(this).attr("class");
		var accion = $(this).attr("accion");
		var id = $(this).attr("id");
		var este = $(this);
		$.ajax({
			url:"<?php echo PUBLIC_PATH ?>company_perfiles/cambiar/"+campo+"/"+accion+"/"+id,
			dataType:"json",
			success:function(r){
				console.log(r)
				if (r.correcto ===  true) {
					este.html(r.imagen);
					console.log(accion,typeof accion)
					if (accion == '1') {
						este.attr("accion",'0')

					}else{

						este.attr("accion",'1')
					}
				}else{
					alert("ocurrio un error")
				}
			}
		})
	})
})
</script>
<style type="text/css">
	.lSAction > .lSPrev { left: 0px !important; }
	.lSNext        { left: 80%; }
	.lSAction >a  {
		background-image: none !important;
		color:;
	}
</style>
