<style type="text/css">
	body{
		background-color:#1f8cd2;
	}
	#header{
		width: 80%;
		margin: auto;
		margin-top:20px;
	}
	#header img{
		width: 100%;
		height: 220px;
	}
	#header .logo{
		background-color:white;
		margin:0px;
	}
	#header .col-md-2,#header .col-md-10{
		padding:0px;
		margin:0px;		
	}
	.mensaje{
		background-color: white;
		padding:20px;
		border:1px solid #8d8986;
		margin:auto;
		width: 80%;
		margin-top:20px;
	}
	.form-horizontal label{
		color:white;
		font-weight: 100;
	}
	.form-control{
		border-radius: 0px;
	}
		.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 10px black;
	}
</style>
<div id="header">
	<div class="row">
		<div class="col-md-2 logo">
			<?php echo Html::img("RECRUITMENT STATION/sears-logo.png") ?>
		</div>
		<div class="col-md-10">
			<?php echo Html::img("RECRUITMENT STATION/shutterstock_2130063162-01.jpg","","width='650' height='140'") ?>
		</div>
	</div>

</div>

<div class="row">
	
	<div class="col-md-12">
		<div class="mensaje ">
			
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero distinctio nemo unde magnam, ipsa, obcaecati rerum quasi illum eum praesentium sunt tempora facilis tenetur. Sapiente eum molestias, dicta corporis mollitia!
		</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<form class="form-horizontal" method="POST">
		<div class="row">
			
			<div class="col-md-8">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
			    <div class="col-sm-10">
			      <input type="email" class="form-control" id="inputEmail3" placeholder="Nombre">
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Sexo</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="inputEmail3" placeholder="Sexo">
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			
			<div class="col-md-8">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">E-mail</label>
			    <div class="col-sm-10">
			      <input type="email" class="form-control" id="inputEmail3" placeholder="E-mail">
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Edad</label>
			    <div class="col-sm-10">
			      <input type="text" class="form-control" id="inputEmail3" placeholder="Edad">
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			
			<div class="col-md-6">
				<div class="form-group">
			    <label for="inputEmail3" class="col-sm-4  text-left">Teléfono 1</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="inputEmail3" placeholder="Teléfono 1">
			    </div>
			  </div>
			</div>
			<div class="col-md-6">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-4  text-left">Teléfono 2</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="inputEmail3" placeholder="Teléfono 2">
			    </div>
			  </div>			
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-1 control-label">Puesto</label>
			    <div class="col-sm-11">
			      <select name="" id="" class="form-control">
			      	<option value="">Vendedor</option>
			      	<option value="">Cajero</option>
			      	<option value="">Ayundate General</option>
			      	<option value="">Mesero</option>
			      	<option value="">Vendedor</option>
			      	<option value="">Almacenista</option>
			      	<option value="">Chofer</option>
			      	<option value="">Limpieza</option>
			      </select>
			    </div>
			  </div>				
			</div>
		</div>
		<div class="row">
			<div class="col-md-6"></div>
			<div class="col-md-6">

			</div>
		</div>
		<div class="row">
			
			<div class="col-md-4">
				<div class="form-group">
			    <div class="col-sm-8">
			      <label><input type="checkbox">&nbsp;Aviso de Privacidad</label>
			    </div>
			  </div>
			</div>
			<div class="col-md-4">
			  <div class="form-group">
			   
			    <div class="col-sm-8">
			      <label><input type="checkbox">&nbsp;Aviso de Privacidad</label>
			    </div>
			  </div>			
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn_crear_empresa">Enviar</button>
					</div>
				</div>
			</div>
		</div>
		
		</form>
	</div>
	<div class="col-md-3"></div>
</div>
<?php View::content() ?>