<html>
<head>
<title>nuevo home-01</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (nuevo home-01.jpg) -->
<table id="Tabla_01" width="1366" height="927" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr>
		<td><center><img src="images/02.png"></center>&nbsp;</td>
	</tr>
	<tr>
	<td width="1366" height="793" align="center" valign="baseline" background="http://empleolisto-rs.com/RS/images/nuevo home_fondo-01.jpg" alt=""> 
<br>
<br>
<br><br>
<span style="font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 300; font-size: 45px;"><br><br><Br><br>Captura a todas las personas que llegan<br>
  a tu empresa a solicitar un empleo<br><br><br>
¡Olvídate del papel y dile hola a lo más nuevo en tecnología!
<br><br><br><br><br><br>
	<br></span>
<center>
		<a href="<?php echo PUBLIC_PATH ?>RS/login" class='boton_app'>Login</a>
	</center><br><br>
	</tr>
</table>
<!-- End Save for Web Slices -->
</body>
</html>