<?php View::content() ?>
<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}

	.fondo{
		padding-top: 10px;
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/man-people-space-desk-1024x683.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		height: 100%;

	}
	#capa{
		position: relative;
		height: auto;
		width:80%;
		margin:auto;
		background: rgba(255, 255, 255, 0.5);
		border-radius: 2px;
		box-shadow: 2px 2px 10px;
		margin-top: 2%;
		margin-bottom: 2%;

	}
	#capa p,#capa li{
		font-size: 22px;
	}
	#capa_letras{
		position: relative;
		padding: 22px;
		margin-bottom: 60px;
	}
	#franja{
		position: relative;
		height: auto;
		width: 100%;
		background-color: white;
		bottom:80px;
		text-align: center;
	}
	.logos{
		padding:10px;
		display: inline-block;

	}
	.logos img{
		height: 80px;
		margin-right: 10px;
	}
	.inditex{
		height: 30px !important;
	}

</style>
  <header>
    <div class="row">
      <div class="col-md-12 logo">
        <h1>empleolisto <br><small>Recruitment Station</small></h1>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-4">
            <?php //echo Html::link("","<p>Nuestras Empresas</p>") ?>
          </div>
          <div class="col-md-4">
          <?php //echo Html::link("","¿Cómo Funciona?") ?>
          </div>
          <div class="col-md-4">
          <?php //echo Html::link("","Contáctanos") ?>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="pull-right div_inicio_sesion">
        </div>
        <div class="clearfix"></div>
      </div>
  		<div class="clearfix"></div>

    </div>
  </header>
<div class="container">
<br>
	<div class=" text-center">
  <h2>Consulta EmpleoListo para renovar tu suscripción</h2>

  <br>
  <p><a class="btn btn-link btn-lg" href="mailto:contacto@empleolisto.com.mx" role="button">contacto@empleolisto.com.mx</a></p>
</div>
</div>