<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	header{
		background-color:#ff7e03;
		height: 100px;
		width: 100%;
		box-shadow: 2px 2px 10px;
	}
	.fondo{
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo_reclutador-05.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		/*height: 100%;*/

	}
	.logo{
		padding:0 !important;
	}
	header a,header p{
		color:white;
		vertical-align: center;
		line-height: 100px;
		font-size: 16px;
	}
	#titulo_pagina{
		color:white;
		font-size: 40px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#titulo_pagina_2{
		color:white;
		font-size: 20px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#form_registro{
		width: 100%;
	}
	#form_registro label{
		font-weight: 100;
		color: white;
	}
	#form_registro input[type="checkbox"]{
	  -ms-transform: scale(2); /* IE */
	  -moz-transform: scale(2); /* FF */
	  -webkit-transform: scale(2); /* Safari and Chrome */
	  -o-transform: scale(2); /* Opera */
	  padding: 10px;
	}
	.checks{
		  -ms-transform: scale(2); /* IE */
		  -moz-transform: scale(2); /* FF */
		  -webkit-transform: scale(2); /* Safari and Chrome */
		  -o-transform: scale(2); /* Opera */
		  padding: 10px;
		  border:1px solid white;
		  background-color: red;
	}
	.checks_text{
		text-align: center;
		color:white;
	}
	.checkboxes{
		margin-top: 20px;
	}
	.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 5px grey;
	}
	.table thead{
		background-color:#ff7e03;
		color:white;
	}
	.iconos_sexo{
		width: 20px;
	}
	.lightSlider img{
		width: 20px;
	}
	.lSAction a:hover,.lSAction a:hover{
		color: #ff7e03 !important;
			
	}

	.lSNext span,.lSPrev span{
		top: 14%;
		font-size: 20px;
		font-weight: bold;
	}
	
	.lSNext,.lSPrev{
		color: #ff7e03;
	}
</style>

<div class="fondo">

	<header>
	    <div class="row">
	      <div class="col-md-3 col-xs-3 logo">
	        <h1>empleolisto <br><small>Recruitment Station</small></h1>
	      </div>
	      <div class="col-md-6 col-xs-6">
	        <div class="row">
	          <div class="col-md-4 col-xs-4">
	            <?php echo Html::link("","<p>Opciones</p>") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verPerfiles","Ver perfiles") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verEmpresas","Ver Empresas") ?>
	          </div>
	        </div>
	      </div>
	      <div class="col-md-3 col-xs-3">
	        <div class="pull-right div_inicio_sesion">
	          <?php echo Html::link("RS/logout","Log out") ?>
	        </div>
	        <div class="clearfix"></div>
	      </div>
	      <div class="clearfix"></div>
	    </div>
	</header>
	
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 text-center">
			<br>

			<form class="form-inline">
			  <div class="form-group">
			    <label style="color:white;font-weight: 100">Puesto</label>
			    <select name="" class="form-control" id="">
			    	<option value="">Puesto 1</option>
			    	<option value="">Puesto 2</option>
			    	<option value="">Puesto 3</option>
			    	<option value="">Puesto 4</option>
			    	<option value="">Puesto 5</option>
			    </select>
			  </div>
			  <div class="form-group">
			    <button class="btn btn-default">Descargar</button>
			  </div>
			</form>
			<br>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<table class="table">
				<thead>
					<th>Nombre</th>
					<th>Edad</th>
					<th>E-mail</th>
					<th>Teléfono</th>
					<th>Fecha de Aplicación</th>
					<th>Sexo</th>
					<th>Status</th>
					<th>Comentarios</th>
				</thead>
				<?php for($i=0;$i<10;$i++): ?>
					<?php if ($i % 2 == 0): ?>
						<tr style="background-color: #d9d9d9">
					<?php else: ?>
						<tr style="background-color: #f3f3f2">
					<?php endif ?>
						<td>Nombre <?php echo $i ?></td>
						<td>Edad <?php echo $i ?></td>
						<td><a href="">E-mail <?php echo $i ?></a></td>
						<td>Teléfono <?php echo $i ?></td>
						<td>Fecha de Aplicación <?php echo $i ?></td>
						<td><?php echo Html::img("RECRUITMENT STATION/iconos h y m-01.png","","class='iconos_sexo'") ?><?php echo Html::img("RECRUITMENT STATION/iconos h y m-04.png","","class='iconos_sexo'") ?></td>
						<td>
							<div style="width:100px">
								
							<ul class="lightSlider">
							  <li><a href="">&nbsp;</a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-02.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-03.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-04.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-05.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-06.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-07.png') ?></a></li>
							  <li><a href=""><?php echo Html::img('RECRUITMENT STATION/iconos2-08.png') ?></a></li>
							  <li><a href="">&nbsp;</a></li>

							</ul>
							</div>							  
						</td>
						<td>Comentarios <?php echo $i ?></td>
					</tr>
				<?php endfor; ?>
			</table>
		</div>
		<div class="col-md-1"></div>
		
	</div>		


</div>
<?php View::content() ?>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>lightslider/dist/css/lightslider.min.css"">
<!-- <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>bootstrap/js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>lightslider/dist/js/lightslider.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){

	$('.lightSlider').lightSlider({
	    item: 3,
	    pager: false,
	    autoWidth: false,
    prevHtml : '<span class="glyphicon glyphicon-chevron-left"></span>',
    nextHtml : '<span class="glyphicon glyphicon-chevron-right"></span>'
	});
})
</script>
<style type="text/css">
	.lSAction > .lSPrev { left: 0px !important; }
	.lSNext        { left: 80%; }
	.lSAction >a  {
		background-image: none !important;
		color:;
	}
</style>
