<?php echo Tag::js("jquery.dataTables.min") ?>
<style type="text/css">
	html,body{
		margin:0px;
		height:100%;
		font-family: Century Gothic, sans-serif;

	}
	header{
		background-color:#ff7e03;
		height: 100px;
		width: 100%;
		box-shadow: 2px 2px 10px;
	}
	.fondo{
		position: relative;
		background-image: url("<?php echo PUBLIC_PATH ?>img/RECRUITMENT STATION/fondo_reclutador-05.jpg");
		background-repeat:no-repeat;
		width: 100%;
		background-size:cover;
		height:100%;
		overflow:auto;
	}
	.logo{
		padding:0 !important;
	}
	header a,header p{
		color:white;
		vertical-align: center;
		line-height: 100px;
		font-size: 16px;
	}
	#titulo_pagina{
		color:white;
		font-size: 40px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#titulo_pagina_2{
		color:white;
		font-size: 20px;
		width: 300px;
		font-weight: bold;
		margin-left: 100px;
	}
	#form_registro{
		width: 100%;
	}
	#form_registro label{
		font-weight: 100;
		color: white;
	}
	#form_registro input[type="checkbox"]{
	  -ms-transform: scale(2); /* IE */
	  -moz-transform: scale(2); /* FF */
	  -webkit-transform: scale(2); /* Safari and Chrome */
	  -o-transform: scale(2); /* Opera */
	  padding: 10px;
	}
	.checks{
		  -ms-transform: scale(2); /* IE */
		  -moz-transform: scale(2); /* FF */
		  -webkit-transform: scale(2); /* Safari and Chrome */
		  -o-transform: scale(2); /* Opera */
		  padding: 10px;
		  border:1px solid white;
		  background-color: red;
	}
	.checks_text{
		text-align: center;
		color:white;
	}
	.checkboxes{
		margin-top: 20px;
	}
	.btn_crear_empresa{
		color:white;
		background-color: #f3910c;
		border:0;
		padding:10px 40px 10px 40px;
		font-size: 25px;
		box-shadow: 3px 3px 5px grey;
	}
	.table thead{
		background-color:#ff7e03;
		color:white;
	}
	.iconos_sexo{
		width: 20px;
	}
	.lightSlider img{
		width: 20px;
	}
	.lSAction a:hover,.lSAction a:hover{
		color: #ff7e03 !important;
			
	}

	.lSNext span,.lSPrev span{
		top: 14%;
		font-size: 20px;
		font-weight: bold;
	}
	
	.lSNext,.lSPrev{
		color: #ff7e03;
	}
</style>

<div class="fondo">

	<header>
	    <div class="row">
	      <div class="col-md-3 col-xs-3 logo">
	      <br>
	      	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo Html::img("logo blanco-02.png","","width='180'") ?>
	      </div>
	      <div class="col-md-6 col-xs-6">
	        <div class="row">
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/superadmin","Nueva Empresa") ?>	          
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verPerfiles","Ver perfiles") ?>
	          </div>
	          <div class="col-md-4 col-xs-4">
	          <?php echo Html::link("RS/verEmpresas","Ver Empresas") ?>
	          </div>
	        </div>
	      </div>
	      <div class="col-md-3 col-xs-3">
	        <div class="pull-right div_inicio_sesion">
	          <?php echo Html::link("RS/logout","Log out") ?>
	        </div>
	        <div class="clearfix"></div>
	      </div>
	      <div class="clearfix"></div>
	    </div>
	</header>
	
	<div class="row">
		<div class="col-md-12 text-center" style="margin-left:10px">
			<br>
			<form class="form-inline" action="<?php echo PUBLIC_PATH ?>RS/verPerfiles">
				  <div class="form-group">
				    <label style="color:white;font-weight: 100">Puesto</label>
				    <select name="puesto" onChange="$(this).parent().parent().submit()" class="form-control" id="">
				    	<option value="">Seleccione</option>
				    	<?php foreach ($puestos as $key => $value): ?>
				    		<?php if (isset($_GET['puesto']) and $_GET['puesto'] == $value->puesto): ?>
					    		<option value="<?php echo $value->puesto ?>" selected><?php echo $value->puesto ?></option>

				    		<?php else: ?>
					    		<option value="<?php echo $value->puesto ?>"><?php echo $value->puesto ?></option>
				    		<?php endif ?>
				    	<?php endforeach ?>
				    </select>
				  </div>
			  
		
				<div class="form-group">
					<select class="form-control" onChange="$(this).parent().parent().submit()" name="sexo">
						<option value="">Sexo</option>

						<option value="M" <?php if(isset($_GET['sexo']) and $_GET['sexo'] == 'M'): echo "selected"; endif;?>>Masculino</option>
						<option value="F" <?php if(isset($_GET['sexo']) and $_GET['sexo'] == 'F'): echo "selected"; endif;?>>Femenino</option>
					</select>
				</div>
				<div class="form-group">
					<select class="form-control" onChange="$(this).parent().parent().submit()" name="edad_desde">
						<option value="">Edad Desde</option>
						<?php for($i=18;$i<81;$i++):?>
							<option value="<?php echo $i ?>" <?php if(isset($_GET['edad_desde']) and $_GET['edad_desde'] == $i): echo "selected"; endif;?>><?php echo $i ?></option>
						<?php endfor;?>
					</select>
					<select class="form-control" onChange="$(this).parent().parent().submit()" name="edad_hasta">
						<option value="">Edad Hasta</option>
						<?php for($i=18;$i<81;$i++):?>
							<option value="<?php echo $i ?>" <?php if(isset($_GET['edad_hasta']) and $_GET['edad_hasta'] == $i): echo "selected"; endif;?>><?php echo $i ?></option>
						<?php endfor;?>
					</select>
				</div>
				<div class="form-group">
					<select class="form-control" onChange="$(this).parent().parent().submit()" name="status">
						<option value="">Status</option>
						<option value="no_aplica" <?php if(isset($_GET['status']) and $_GET['status'] == 'no_aplica'): echo "selected"; endif;?>>No aplica</option>
						<option value="aplico" <?php if(isset($_GET['status']) and $_GET['status'] == 'aplico'): echo "selected"; endif;?>>Aplicó</option>
						<option value="llamar" <?php if(isset($_GET['status']) and $_GET['status'] == 'llamar'): echo "selected"; endif;?>>Llamar</option>
						<option value="entrevista1" <?php if(isset($_GET['status']) and $_GET['status'] == 'entrevista1'): echo "selected"; endif;?>>Entrevista 1</option>
						<option value="entrevista2" <?php if(isset($_GET['status']) and $_GET['status'] == 'entrevista2'): echo "selected"; endif;?>>Entrevista 2</option>
						<option value="medico" <?php if(isset($_GET['status']) and $_GET['status'] == 'medico'): echo "selected"; endif;?>>Médico</option>
						<option value="documentos" <?php if(isset($_GET['status']) and $_GET['status'] == 'documentos'): echo "selected"; endif;?>>Documentos</option>
						<option value="contrato" <?php if(isset($_GET['status']) and $_GET['status'] == 'contrato'): echo "selected"; endif;?>>Contrato</option>
					</select>
				</div>
			    <button class="btn btn-default" name="excel" value="1">Descargar</button>
			    <?php echo Html::link("RS/verPerfiles","Reset","class='btn btn-default'") ?>
			</form>
			<br><br>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-1"></div>
		<div class="col-md-10">
				<?php if (count($perfiles)): ?>
				<?php else: ?>
			<center>
				<h3>No se Encontraron Registros</h3>
			</center>
			<?php endif ?>
					<table class="table datatable">
						<thead>
							<th>Nombre</th>
							<th>Edad</th>
							<th>E-mail</th>
							<th>Teléfono</th>
							<th>Fecha de Aplicación</th>
							<th>Sexo</th>
							<th>Status</th>
							<th>Puesto</th>
							<th>Comentarios</th>
							<th></th>
						</thead>
					
						<?php for($i=0;$i<count($perfiles->items);$i++): ?>
							<?php if ($i % 2 == 0): ?>
								<tr style="background-color: #F6F6F6">
							<?php else: ?>
								<tr style="background-color: #f3f3f2">
							<?php endif ?>
								<td> <?php echo $perfiles->items[$i]->nombre ?></td>
								<td><?php echo $perfiles->items[$i]->edad ?></td>
								<td><?php echo $perfiles->items[$i]->email ?></td>
								<td><?php echo $perfiles->items[$i]->telefono1 ?> | <?php echo $perfiles->items[$i]->telefono2 ?></td>
								<td><?php echo $perfiles->items[$i]->created ?></td>
								<td>
						<?php if ($perfiles->items[$i]->sexo == "M"): ?>
						<?php echo Html::img("RECRUITMENT STATION/iconos h y m-01.png","","class='iconos_sexo'") ?>
						<?php else: ?>
						<?php echo Html::img("RECRUITMENT STATION/iconos h y m-02.png","","class='iconos_sexo'") ?>

						<?php endif ?>
									
								</td>
								<td>
									<div style="width:100px">
										
									<ul class="lightSlider">
									  <li><a href="">&nbsp;</a></li>

									  <?php if ($perfiles->items[$i]->no_aplica): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-02.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-02.png') ?></li>
									  <?php endif ?>


									  <?php if ($perfiles->items[$i]->aplico): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-03.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-03.png') ?></li>
									  <?php endif ?>

									  <?php if ($perfiles->items[$i]->llamar): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-01.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-01.png') ?></li>
									  <?php endif ?>


									  <?php if ($perfiles->items[$i]->entrevista1): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-04.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-04.png') ?></li>
									  <?php endif ?>


									  <?php if ($perfiles->items[$i]->entrevista2): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-05.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-05.png') ?></li>
									  <?php endif ?>

									  <?php if ($perfiles->items[$i]->medico): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-06.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-06.png') ?></li>
									  <?php endif ?>

									  <?php if ($perfiles->items[$i]->documentos): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-08.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-08.png') ?></li>
									  <?php endif ?>


									  <?php if ($perfiles->items[$i]->contrato): ?>
									  	<li><?php echo Html::img('RECRUITMENT STATION/iconos2-07.png') ?></li>
										<?php else: ?>
											<li><?php echo Html::img('RECRUITMENT STATION/iconos2_byn-07.png') ?></li>
									  <?php endif ?>

									  <li><a href="#">&nbsp;</a></li>

									</ul>
									</div>							  
								</td>
								<td><?php echo $perfiles->items[$i]->puesto ?></td>
								<td style="width:200px" class="comentarios" id="<?php echo $perfiles->items[$i]->id ?>">
									<?php if (!$perfiles->items[$i]->comentario): ?>
										Deja un Comentario
									<?php else: ?>
										<?php echo $perfiles->items[$i]->comentario ?>
									<?php endif ?>
								</td>
								<td>
												

										<button type="button" class="btn btn-default popup" data-toggle="popover" data-placement="left" title="Experiencia Laboral" data-content="<?php echo $perfiles->items[$i]->experiencia ?>">Experiencia</button>
									
								</td>
							</tr>
						<?php endfor; ?>
					</table>
								<?php if($perfiles->prev) echo Html::link('RS/verPerfiles/'.$perfiles->prev, 'Anterior') ?>
<?php if($perfiles->next) echo ' | ' . Html::link('RS/verPerfiles/'.$perfiles->next, 'Siguiente') ?>
	<br>
	<br>
		</div>
		<div class="col-sm-1"></div>
		
	</div>		


</div>
<?php View::content() ?>
<style type="text/css">
	.dataTables_paginate a{
		padding-left:10px;
	}
	.dataTables_paginate a:hover{
		cursor:pointer;
	}
</style>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>lightslider/dist/css/lightslider.min.css"">
<!-- <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>bootstrap/js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>lightslider/dist/js/lightslider.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".datatable").DataTable({
		paginate:false,
		"info":     false,
		"searching": false,
		language:{
		    "sProcessing":     "Procesando...",
		    "sLengthMenu":     "Mostrar _MENU_ registros",
		    "sZeroRecords":    "No se encontraron resultados",
		    "sEmptyTable":     "Ningún dato disponible en esta tabla",
		    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
		    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
		    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
		    "sInfoPostFix":    "",
		    "sSearch":         "Buscar:",
		    "sUrl":            "",
		    "sInfoThousands":  ",",
		    "sLoadingRecords": "Cargando...",
		    "oPaginate": {
		        "sFirst":    "Primero",
		        "sLast":     "Último",
		        "sNext":     "Siguiente",
		        "sPrevious": "Anterior"
		    },
		    "oAria": {
		        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
		        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
		    }
		}
	});
	$('.lightSlider').lightSlider({
	    item: 3,
	    pager: false,
	    autoWidth: false,
    prevHtml : '<span class="glyphicon glyphicon-chevron-left"></span>',
    nextHtml : '<span class="glyphicon glyphicon-chevron-right"></span>'
	});
	$("body").on("blur",".comentarios",function(){
		console.log("EDITO!")
		var text = $.trim($(this).text());
		var este = $(this);
		$.ajax({
			url:"<?php echo PUBLIC_PATH ?>company_perfiles/editarComentario/"+$(this).attr("id"),
			type:"POST",
			data:{comentario:text},
			dataType:"json",
			success:function(r){
				if (r.correcto === false) {
					alert("Ocurrio un error guardando el comentario!");
					este.text("Deja un Comentario");
				}
			}
		});
	})
	/*$("body").on("click",".lightSlider a",function(e){
		e.preventDefault();
		var campo = $(this).attr("class");
		var accion = $(this).attr("accion");
		var id = $(this).attr("id");
		var este = $(this);
		$.ajax({
			url:"<?php echo PUBLIC_PATH ?>company_perfiles/cambiar/"+campo+"/"+accion+"/"+id,
			dataType:"json",
			success:function(r){
				console.log(r)
				if (r.correcto ===  true) {
					este.html(r.imagen);
					console.log(accion,typeof accion)
					if (accion == '1') {
						este.attr("accion",'0')

					}else{

						este.attr("accion",'1')
					}
				}else{
					alert("ocurrio un error")
				}
			}
		})
	})*/
	
})
</script>
<style type="text/css">
	.lSAction > .lSPrev { left: 0px !important; }
	.lSNext        { left: 80%; }
	.lSAction >a  {
		background-image: none !important;
		color:;
	}
</style>
