<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>EmpleoListo</title>
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>bootstrap/css/bootstrap.min.css">
  <?php echo Tag::css("estilos") ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("jquery-1.12.4.min") ?>
</head>
<body>
  <?php View::content(); ?>
</body>
</html>
